# Generated by Django 5.1 on 2024-09-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Furniture', 'Furniture'), ('Clothing', 'Clothing'), ('Books', 'Books'), ('Food', 'Food'), ('Food_Items', 'Food Items'), ('Health', 'Health'), ('Other', 'Other')], max_length=20),
        ),
    ]
